services:
  mopidy:
    container_name: mopidy
    image: jjok/mopidy:latest
    devices:
      - /dev/snd
    volumes:
      - ~/Music:/root/Music:ro
    restart: unless-stopped
    environment:
      - PULSE_SERVER=tcp:host.containers.internal:4713 # PipeWire audio forwarding
    network_mode: host
